name: Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  rails-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        node-version: [16.x, 18.x]
    steps:

    - uses: actions/checkout@v3
    - name: Setup docker
      run: cd tests/rails && docker compose up --build -d && curl -m 10 --retry 10 -I 0.0.0.0:9000/minio/health/live

    - name: Install libvips
      run: sudo apt -y install libvips

    - name: Set parallel workers env variable
      run: echo "PARALLEL_WORKERS=$(expr $(nproc) \* 6)" >> $GITHUB_ENV

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - uses: pnpm/action-setup@v2
      with:
        version: 7.x.x
        run_install: false

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
          tests/rails/pnpm-lock.yaml

    - name: Install via pnpm
      run: |
        pnpm run setup
    - name: Tests
      run: |
        pnpm run build
        pnpm run test:ci
        

    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: capybara ${{ matrix.ruby }} ${{ matrix.node-version }}
        path: tests/rails/tmp/capybara/
        retention-days: 5

    - uses: actions/upload-artifact@v3
      if: ${{ failure() || success() }}
      with:
        name: log ${{ matrix.ruby }} ${{ matrix.node-version }}
        path: tests/rails/log/
        retention-days: 5
